### ISSUE TITLE
AttributeError: 'collections.OrderedDict' object has no attribute 'data'

### ISSUE THREAD

**Issue by manumora** [Channelstream/channelstream#9]
Running
`YOUR_PYTHON_ENV/bin/channelstream`

This error appears in console:
>   File "/home/manu/workspace/channelstream/channelstream/wsgi_views/server.py", line 145, in connect
>     json_body = schema.load(request.json_body).data
> AttributeError: 'collections.OrderedDict' object has no attribute 'data'

Executed under python3.7

**Comment by ergo** [comment]
Hi, can you tell me what version of Marshmallow are you using? (And did you install channelstream in a separate venv?)
Seems to me there was an API change on Marshmallow end.

**Comment by manumora** [comment]
> Hi, can you tell me what version of Marshmallow are you using?
marshmallow==3.0.0rc3

> (And did you install channelstream in a separate venv?)
As chat demo doesn't have setup.py file It wasn't installed in a separated venv, both are being executed in the same venv.

**Comment by ergo** [comment]
Try installing marshmallow==2.16.1, it will fix everything for you, I will later make a release that pins down marshmallow to not include their 3.x releases.

**Comment by manumora** [comment]
Now works fine.
Thank you for your quick response!

**Comment by ergo** [comment]
I've made a new release, I'm not sure how you ended up with 3.x-rc (I couldn't replicate) but this release pins Marshmallow to 2.x.
